// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: commands.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	commands.proto

It has these top-level messages:
	RegisterUser
	ResetPassword
*/
package main

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RegisterUser struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *RegisterUser) Reset()                    { *m = RegisterUser{} }
func (m *RegisterUser) String() string            { return proto.CompactTextString(m) }
func (*RegisterUser) ProtoMessage()               {}
func (*RegisterUser) Descriptor() ([]byte, []int) { return fileDescriptorCommands, []int{0} }

func (m *RegisterUser) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ResetPassword struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
}

func (m *ResetPassword) Reset()                    { *m = ResetPassword{} }
func (m *ResetPassword) String() string            { return proto.CompactTextString(m) }
func (*ResetPassword) ProtoMessage()               {}
func (*ResetPassword) Descriptor() ([]byte, []int) { return fileDescriptorCommands, []int{1} }

func (m *ResetPassword) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUser)(nil), "main.RegisterUser")
	proto.RegisterType((*ResetPassword)(nil), "main.ResetPassword")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptorCommands) }

var fileDescriptorCommands = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc,
	0x93, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcf, 0x4f,
	0xcf, 0xd7, 0x07, 0x4b, 0x26, 0x95, 0xa6, 0x81, 0x79, 0x60, 0x0e, 0x98, 0x05, 0xd1, 0xa4, 0xa4,
	0xc6, 0xc5, 0x13, 0x94, 0x9a, 0x9e, 0x59, 0x5c, 0x92, 0x5a, 0x14, 0x5a, 0x9c, 0x5a, 0x24, 0x24,
	0xc6, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0xe9, 0xc4, 0xf6, 0xe8, 0x9e, 0x3c,
	0x93, 0xa7, 0x4b, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x3c, 0x17, 0x6f, 0x50, 0x6a, 0x71, 0x6a, 0x49,
	0x40, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x10, 0x1f, 0x17, 0x93, 0xa7, 0x0b, 0x44, 0x61,
	0x10, 0x53, 0xa6, 0x4b, 0x12, 0x1b, 0xd8, 0x3c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69,
	0xbf, 0x52, 0x4c, 0x96, 0x00, 0x00, 0x00,
}
