// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: event.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	A
	B
	EventContainer
*/
package main

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type A struct {
	ID      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At      int64  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
}

func (m *A) Reset()                    { *m = A{} }
func (m *A) String() string            { return proto.CompactTextString(m) }
func (*A) ProtoMessage()               {}
func (*A) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{0} }

func (m *A) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *A) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *A) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

type B struct {
	ID         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version    int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At         int64  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ExternalID string `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
}

func (m *B) Reset()                    { *m = B{} }
func (m *B) String() string            { return proto.CompactTextString(m) }
func (*B) ProtoMessage()               {}
func (*B) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{1} }

func (m *B) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *B) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *B) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *B) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *B) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

type EventContainer struct {
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Ma   *A    `protobuf:"bytes,2,opt,name=ma" json:"ma,omitempty"`
	Mb   *B    `protobuf:"bytes,3,opt,name=mb" json:"mb,omitempty"`
}

func (m *EventContainer) Reset()                    { *m = EventContainer{} }
func (m *EventContainer) String() string            { return proto.CompactTextString(m) }
func (*EventContainer) ProtoMessage()               {}
func (*EventContainer) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{2} }

func (m *EventContainer) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *EventContainer) GetMa() *A {
	if m != nil {
		return m.Ma
	}
	return nil
}

func (m *EventContainer) GetMb() *B {
	if m != nil {
		return m.Mb
	}
	return nil
}

func init() {
	proto.RegisterType((*A)(nil), "main.a")
	proto.RegisterType((*B)(nil), "main.b")
	proto.RegisterType((*EventContainer)(nil), "main.event_container")
}

func init() { proto.RegisterFile("event.proto", fileDescriptorEvent) }

var fileDescriptorEvent = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0xe5, 0xd7, 0xa4, 0x15, 0x2f, 0x52, 0x91, 0x3c, 0x80, 0xc5, 0xd2, 0x28, 0x53, 0x16,
	0x12, 0x09, 0xfe, 0x00, 0xb5, 0x43, 0x56, 0x2f, 0x8c, 0xd5, 0x73, 0x63, 0x82, 0x25, 0x6c, 0x57,
	0xc1, 0xad, 0xe0, 0x17, 0xf8, 0xc8, 0x0e, 0xfd, 0x12, 0x94, 0x07, 0xe5, 0x07, 0xd8, 0xee, 0xf5,
	0xf5, 0x3b, 0xba, 0xba, 0x58, 0xd8, 0xa3, 0x0d, 0xa9, 0xd9, 0x8f, 0x31, 0x45, 0x99, 0x79, 0x72,
	0xe1, 0xee, 0x7e, 0x70, 0xe9, 0xf5, 0x60, 0x9a, 0x5d, 0xf4, 0xed, 0x10, 0x87, 0xd8, 0x72, 0x68,
	0x0e, 0x2f, 0xec, 0xd8, 0xb0, 0xfa, 0x39, 0xaa, 0x36, 0x28, 0x48, 0xde, 0x20, 0xb8, 0x5e, 0x89,
	0x52, 0xd4, 0x57, 0x4f, 0xf3, 0xf3, 0x69, 0x05, 0xdd, 0x5a, 0x83, 0xeb, 0xa5, 0xc2, 0xc5, 0xd1,
	0x8e, 0xef, 0x2e, 0x06, 0x05, 0xa5, 0xa8, 0x73, 0x7d, 0xb1, 0x72, 0x89, 0x40, 0x49, 0xcd, 0x4a,
	0x51, 0xcf, 0x34, 0x50, 0xaa, 0xbe, 0x04, 0x0a, 0xf3, 0x7f, 0x8e, 0x94, 0x98, 0x05, 0xf2, 0x56,
	0x65, 0x13, 0x43, 0xb3, 0x96, 0x2d, 0x16, 0xf6, 0x23, 0xd9, 0x31, 0xd0, 0xdb, 0xd6, 0xf5, 0x2a,
	0x67, 0xfc, 0xf2, 0x7c, 0x5a, 0xe1, 0xe6, 0xf7, 0xb9, 0x5b, 0x6b, 0xbc, 0x7c, 0xe9, 0xfa, 0xea,
	0x19, 0xaf, 0x79, 0x97, 0xed, 0x2e, 0x86, 0x44, 0x2e, 0xd8, 0x71, 0xe2, 0xa6, 0xcf, 0xbd, 0xe5,
	0x6e, 0xb9, 0x66, 0x2d, 0x6f, 0x11, 0x3c, 0x71, 0xa1, 0xe2, 0x61, 0xd1, 0x4c, 0xe3, 0x35, 0xa4,
	0xc1, 0x13, 0x07, 0x86, 0x4b, 0xfd, 0x05, 0x46, 0x83, 0x37, 0x66, 0xce, 0x9b, 0x3d, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0x31, 0x96, 0x74, 0x77, 0x01, 0x00, 0x00,
}
