// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	events.proto

It has these top-level messages:
	A
	B
	EventContainer
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type A struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	At      int64  `protobuf:"varint,3,opt,name=at" json:"at,omitempty"`
}

func (m *A) Reset()                    { *m = A{} }
func (m *A) String() string            { return proto.CompactTextString(m) }
func (*A) ProtoMessage()               {}
func (*A) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *A) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *A) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *A) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

type B struct {
	ID      string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=Version,json=version" json:"Version,omitempty"`
	At      int64  `protobuf:"varint,3,opt,name=At,json=at" json:"At,omitempty"`
	Name    string `protobuf:"bytes,4,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *B) Reset()                    { *m = B{} }
func (m *B) String() string            { return proto.CompactTextString(m) }
func (*B) ProtoMessage()               {}
func (*B) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *B) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *B) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *B) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *B) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EventContainer struct {
	Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Ma   *A    `protobuf:"bytes,2,opt,name=ma" json:"ma,omitempty"`
	Mb   *B    `protobuf:"bytes,3,opt,name=mb" json:"mb,omitempty"`
}

func (m *EventContainer) Reset()                    { *m = EventContainer{} }
func (m *EventContainer) String() string            { return proto.CompactTextString(m) }
func (*EventContainer) ProtoMessage()               {}
func (*EventContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EventContainer) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *EventContainer) GetMa() *A {
	if m != nil {
		return m.Ma
	}
	return nil
}

func (m *EventContainer) GetMb() *B {
	if m != nil {
		return m.Mb
	}
	return nil
}

func init() {
	proto.RegisterType((*A)(nil), "main.a")
	proto.RegisterType((*B)(nil), "main.b")
	proto.RegisterType((*EventContainer)(nil), "main.event_container")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x91, 0x2c, 0xd7, 0xf4, 0x5a, 0x5a, 0xd0, 0x12, 0x8d, 0xc6, 0x93, 0x27, 0x0f, 0xc9,
	0x9c, 0x21, 0xe0, 0x25, 0x4b, 0x20, 0x1a, 0x92, 0x31, 0x9c, 0x62, 0x0d, 0x1a, 0x24, 0x19, 0x5b,
	0x18, 0xf2, 0xef, 0x83, 0x0e, 0x62, 0xb2, 0x64, 0x93, 0xee, 0xbd, 0xef, 0xde, 0x3d, 0xf8, 0xb5,
	0x8b, 0x0d, 0x69, 0xee, 0xc6, 0x29, 0xa6, 0x28, 0x85, 0x47, 0x17, 0x9a, 0x3d, 0x30, 0x94, 0x7f,
	0xc0, 0xdd, 0xa0, 0x58, 0xcd, 0xda, 0x6f, 0xcd, 0xdd, 0x20, 0x15, 0x54, 0x8b, 0x9d, 0x66, 0x17,
	0x83, 0xe2, 0x35, 0x6b, 0x4b, 0xfd, 0xfa, 0x66, 0x27, 0x26, 0x55, 0xd4, 0xac, 0x2d, 0x34, 0xc7,
	0xd4, 0x9c, 0x81, 0x99, 0x3c, 0x3c, 0xf6, 0x2b, 0xde, 0x67, 0xfc, 0xf2, 0x11, 0x3f, 0xbc, 0xe1,
	0x52, 0x82, 0x38, 0xa1, 0xb7, 0x4a, 0x10, 0x2b, 0x02, 0x7a, 0xdb, 0x5c, 0xe1, 0x9f, 0xee, 0xbc,
	0xdd, 0x63, 0x48, 0xe8, 0x82, 0x9d, 0xb2, 0x2d, 0x3d, 0x46, 0x4b, 0x11, 0xa5, 0xa6, 0xb7, 0xdc,
	0x00, 0xf7, 0x48, 0xfb, 0x7f, 0xb6, 0x55, 0x97, 0xbb, 0x74, 0xa8, 0xb9, 0x47, 0x12, 0x0c, 0x65,
	0xac, 0x82, 0xd1, 0xdc, 0x1b, 0xf3, 0x45, 0xbd, 0x77, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4,
	0xfd, 0xb4, 0xe7, 0x07, 0x01, 0x00, 0x00,
}
